### ISSUE TITLE
Load siteKey and secretKey from server specific settings.yaml

### ISSUE THREAD

**Issue by simonschaufi** [die-wegmeister/Wegmeister.Recaptcha#16]
### Description

Since it's not good to store secret keys in the git repository, I want to store them in settings.yaml that are not in git but loaded depending on the server environment. Is that possible?

This package supports that https://github.com/gerdemann/Gerdemann.ReCAPTCHA but has less configuration options

**Comment by Benjamin-K** [comment]
Hey @simonschaufi,

you can simply add your secret key in the Settings.yaml by overriding the default rendering options like this:

```yaml
Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Wegmeister.Recaptcha:Captcha':
            properties:
              siteKey: 'your-public-key'
              secretKey: 'your-private-key'
```

Hope this helps 😉
